# timeout setting, unit: ms, default 30000

uint32 charging
uint32 charging_off
uint32 loading
uint32 unloading
uint32 equip_not_send_req
uint32 equip_not_send_ready
uint32 equip_not_off_ready
uint32 equip_not_off_lreq
uint32 equip_not_off_ureq

---

bool result
